apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gpushare-installer.fullname" . }}
  labels:
    app: {{ template "gpushare-installer.name" . }}
    chart: {{ template "gpushare-installer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.masterCount }}
  selector:
    matchLabels:
      app: {{ template "gpushare-installer.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels: 
        app: {{ template "gpushare-installer.name" . }}
        chart: {{ template "gpushare-installer.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        operator: Exists
        key: node.cloudprovider.kubernetes.io/uninitialized
      nodeSelector:
         node-role.kubernetes.io/master: ""
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "gpushare-installer.name" . }}
            topologyKey: kubernetes.io/hostname
      containers:
      - name: deploy-schd
        image: {{ .Values.schdInstallerImage }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command: 
          - /schd-extender/install-sched-extender.sh
          - --version
          - {{ .Values.kubeVersion }}
        volumeMounts:
        - name: k8s-host
          mountPath: /k8s-host
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: k8s-host